From python:3.4

RUN pip install Flask==0.10.1 uWSGI==2.0.10
WORKDIR /app
Copy app /app

CMD ["uwsgi", "--http", "0.0.0.0:9090", "--wsgi-file", "/app/identidock.py", "--callable", "app", "--stats", "0.0.0.0:9191"]
